title = "mdpad: one-file web apps"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
# summaryLength = 30

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Details"
    url = "/details/"
    weight = 2

[[menu.main]]
    name = "Examples"
    url = "/examples/"
    weight = 3

[[menu.main]]
    name = "Github"
    url = "https://github.com/tshort/mdpad-js"
    weight = 4

[params]
  google_analytics_id=""


  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

